global using Carter;
global using Mapster;
global using MediatR;
global using BuildingBlocks.CQRS;
global using Catalog.API.Models;
global using FluentValidation;
global using Catalog.API.Data;
global using Microsoft.EntityFrameworkCore;
global using BuildingBlocks.Exceptions;
